# Dependencies
#markdown:            redcarpet
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:day/:title/
#relative_permalinks: true

# Setup
title:            Agus
tagline:          'Belajar, Menulis Kode dan Berbagi.'
description:      'Simple tools for.'
url:              http://www.agus.pro/id

author:
  name:           'Agus Suhartono'
  url:            http://www.agus.pro/id
  gravatar:       https://en.gravatar.com/agussuhartono
  photo:          https://secure.gravatar.com/avatar/01eed2065469bcf386582acb1f0671c8
  introduction:   'Seoarang suami dan ayah bagi 4 orang anak. <a href="/id/about/">Tentang saya...</a>.'

paginate:         10
paginate_path:    '/blog/page:num'

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/agussuhartono/
